/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppVehiculeRouteImport } from './routes/_app.vehicule'
import { Route as AppTresorerieRouteImport } from './routes/_app.tresorerie'
import { Route as AppParametresRouteImport } from './routes/_app.parametres'
import { Route as AppImmobilierRouteImport } from './routes/_app.immobilier'
import { Route as AppDepensesRouteImport } from './routes/_app.depenses'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCrmRouteImport } from './routes/_app.crm'
import { Route as AppComptabiliteRouteImport } from './routes/_app.comptabilite'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVehiculeRoute = AppVehiculeRouteImport.update({
  id: '/vehicule',
  path: '/vehicule',
  getParentRoute: () => AppRoute,
} as any)
const AppTresorerieRoute = AppTresorerieRouteImport.update({
  id: '/tresorerie',
  path: '/tresorerie',
  getParentRoute: () => AppRoute,
} as any)
const AppParametresRoute = AppParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => AppRoute,
} as any)
const AppImmobilierRoute = AppImmobilierRouteImport.update({
  id: '/immobilier',
  path: '/immobilier',
  getParentRoute: () => AppRoute,
} as any)
const AppDepensesRoute = AppDepensesRouteImport.update({
  id: '/depenses',
  path: '/depenses',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCrmRoute = AppCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AppRoute,
} as any)
const AppComptabiliteRoute = AppComptabiliteRouteImport.update({
  id: '/comptabilite',
  path: '/comptabilite',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/comptabilite': typeof AppComptabiliteRoute
  '/crm': typeof AppCrmRoute
  '/dashboard': typeof AppDashboardRoute
  '/depenses': typeof AppDepensesRoute
  '/immobilier': typeof AppImmobilierRoute
  '/parametres': typeof AppParametresRoute
  '/tresorerie': typeof AppTresorerieRoute
  '/vehicule': typeof AppVehiculeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/comptabilite': typeof AppComptabiliteRoute
  '/crm': typeof AppCrmRoute
  '/dashboard': typeof AppDashboardRoute
  '/depenses': typeof AppDepensesRoute
  '/immobilier': typeof AppImmobilierRoute
  '/parametres': typeof AppParametresRoute
  '/tresorerie': typeof AppTresorerieRoute
  '/vehicule': typeof AppVehiculeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/comptabilite': typeof AppComptabiliteRoute
  '/_app/crm': typeof AppCrmRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/depenses': typeof AppDepensesRoute
  '/_app/immobilier': typeof AppImmobilierRoute
  '/_app/parametres': typeof AppParametresRoute
  '/_app/tresorerie': typeof AppTresorerieRoute
  '/_app/vehicule': typeof AppVehiculeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/comptabilite'
    | '/crm'
    | '/dashboard'
    | '/depenses'
    | '/immobilier'
    | '/parametres'
    | '/tresorerie'
    | '/vehicule'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/comptabilite'
    | '/crm'
    | '/dashboard'
    | '/depenses'
    | '/immobilier'
    | '/parametres'
    | '/tresorerie'
    | '/vehicule'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/_app/comptabilite'
    | '/_app/crm'
    | '/_app/dashboard'
    | '/_app/depenses'
    | '/_app/immobilier'
    | '/_app/parametres'
    | '/_app/tresorerie'
    | '/_app/vehicule'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/vehicule': {
      id: '/_app/vehicule'
      path: '/vehicule'
      fullPath: '/vehicule'
      preLoaderRoute: typeof AppVehiculeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tresorerie': {
      id: '/_app/tresorerie'
      path: '/tresorerie'
      fullPath: '/tresorerie'
      preLoaderRoute: typeof AppTresorerieRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/parametres': {
      id: '/_app/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof AppParametresRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/immobilier': {
      id: '/_app/immobilier'
      path: '/immobilier'
      fullPath: '/immobilier'
      preLoaderRoute: typeof AppImmobilierRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/depenses': {
      id: '/_app/depenses'
      path: '/depenses'
      fullPath: '/depenses'
      preLoaderRoute: typeof AppDepensesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/crm': {
      id: '/_app/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof AppCrmRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/comptabilite': {
      id: '/_app/comptabilite'
      path: '/comptabilite'
      fullPath: '/comptabilite'
      preLoaderRoute: typeof AppComptabiliteRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppComptabiliteRoute: typeof AppComptabiliteRoute
  AppCrmRoute: typeof AppCrmRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDepensesRoute: typeof AppDepensesRoute
  AppImmobilierRoute: typeof AppImmobilierRoute
  AppParametresRoute: typeof AppParametresRoute
  AppTresorerieRoute: typeof AppTresorerieRoute
  AppVehiculeRoute: typeof AppVehiculeRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppComptabiliteRoute: AppComptabiliteRoute,
  AppCrmRoute: AppCrmRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDepensesRoute: AppDepensesRoute,
  AppImmobilierRoute: AppImmobilierRoute,
  AppParametresRoute: AppParametresRoute,
  AppTresorerieRoute: AppTresorerieRoute,
  AppVehiculeRoute: AppVehiculeRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
